<?php

namespace AppModule\DI;


use Flame\Modules\Configurators\IPresenterMappingConfig;
use Flame\Modules\Providers\IPresenterMappingProvider;
use Flame\Modules\Providers\IRouterProvider;
use Nette;
use Nette\Application\Routers\Route;
use Nette\Application\Routers\RouteList;
use Nette\DI\CompilerExtension;
use Nette\PhpGenerator\ClassType;


/**
 * @author Pavel Paulík
 */
class AppExtension extends CompilerExtension
    implements
    \Kdyby\Doctrine\DI\IEntityProvider,
    IPresenterMappingProvider
//    IRouterProvider
{

    const TAG_ROUTE = 'devrun.route';
    const TAG_SUBSCRIBER = 'kdyby.subscriber';


    /** @var mixed[] */
    public $defaults = array(
        'session' => array(),
        'website' => array(
            'routePrefix'      => 'prefix_',
            'defaultPresenter' => 'App:Default',
            'authentication'   => array(
                'autologin'        => null,
                'autoregistration' => null,
            ),
        ),
        'paths'   => array(
            'publicDir' => '%wwwDir%/public',
            'dataDir'   => '%appDir%/data',
            'logDir'    => '%appDir%/../log',
        ),
    );

    private $_lang = 'cs';

    /**
     * Processes configuration data. Intended to be overridden by descendant.
     *
     * @return void
     */
    public function loadConfiguration()
    {
        $this->compiler->parseServices(
            $this->getContainerBuilder(),
            $this->loadFromFile(dirname(dirname(__DIR__)) . '/Resources/config/config.neon')
        );

        $builder = $this->getContainerBuilder();
        $config  = $this->getConfig($this->defaults);
        $params = $builder->parameters;

        // forms
        $builder->addDefinition($this->prefix('forms.registrationFormFactory'))
            ->setImplement('AppModule\Forms\IRegistrationFormFactory')
            ->addSetup('create');

        $builder->addDefinition($this->prefix('forms.loginFormFactory'))
            ->setImplement('AppModule\Forms\ILoginFormFactory')
            ->addSetup('create');

        $builder->addDefinition($this->prefix('forms.lostPswFormFactory'))
            ->setImplement('AppModule\Forms\ILostPswFormFactory')
            ->addSetup('create');

        $builder->addDefinition($this->prefix('forms.quizFormFactory'))
            ->setImplement('AppModule\Forms\IQuizFormFactory')
            ->addSetup('create');

        // routers
        $builder->addDefinition($this->prefix('router.default'))
            ->setClass('AppModule\Routers\RouterFactory');

        $builder->addDefinition($this->prefix('router.listener'))
            ->setClass('CmsModule\Doctrine\Listeners\TablePrefixListener', [$config['website']['routePrefix']]);

        $lang = $builder->parameters['lang'];
        $this->_lang = $lang;

        // entities
        $builder->addDefinition($this->prefix('entities.user'))
            ->setClass('AppModule\Entities\UserEntity');

        $builder->addDefinition($this->prefix('entities.question'))
            ->setClass('AppModule\Entities\QuestionEntity');

        // subscribers
        $builder->addDefinition($this->prefix('listener.transactionListener'))
            ->setClass('AppModule\Managers\TransactionListener', [$builder->parameters['contest']])
            ->addTag(self::TAG_SUBSCRIBER);

    }

    public function _beforeCompile()
    {
        parent::beforeCompile(); // TODO: Change the autogenerated stub

        $builder = $this->getContainerBuilder();

        $lang = $builder->parameters['lang'];
        $this->_lang = $lang;
    }


    public function _afterCompile(ClassType $class)
    {
        parent::afterCompile($class);
        $builder = $this->getContainerBuilder();

        $lang = $builder->parameters['lang'];
        $this->_lang = $lang;
    }


    /**
     * Setup presenter mapping : ClassNameMask => PresenterNameMask
     *
     * @param IPresenterMappingConfig &$presenterMappingConfig
     *
     * @return void
     */
    public function setupPresenterMapping(IPresenterMappingConfig &$presenterMappingConfig)
    {
        $presenterMappingConfig->setMapping('App', 'AppModule\*Module\Presenters\*Presenter'); // example from cms module
    }


    /**
     * Returns array of ServiceDefinition,
     * that will be appended to setup of router service
     *
     * @return \Nette\Application\IRouter
     */
    public function getRoutesDefinition()
    {
        $router   = new RouteList();
        $router[] = new Route('index.php', 'App:Registration:default', Route::ONE_WAY);

        $router[]      = $adminRouter = new RouteList('Cms');
        $adminRouter[] = new Route('admin/[<locale=cs cs|en>/]<presenter>/<action>[/<id>]', array(
            'presenter' => 'Dashboard',
            'action'    => 'default'
        ));

        $router[] = $frontRouter = new RouteList('App');
        $frontRouter[] = new Route('sitemap.xml', array('presenter' => 'Sitemap', 'action' => 'sitemap',));
        $frontRouter[] = new Route('clear', array('presenter' => 'Homepage', 'action' => 'clearCache',));

        // detect prefix
        $mask = sprintf("[<locale=%s %s>/]<slug .+>[/<presenter>/<action>[/<id>]]", 'cs', 'cs|en');

        $frontRouter[] = new Route("[<locale={$this->_lang} sk|hu|cs>/]<presenter>/<action>[/<id>]", array(
                'presenter' => array(
                    Route::VALUE        => 'Homepage',
                    Route::FILTER_TABLE => array(),
                ),
                'action'    => array(
                    Route::VALUE        => 'default',
                    Route::FILTER_TABLE => array(
                        'odeslana' => 'send',
                    ),
                ),
            )
        );

        return $router;
    }


    /**
     * Returns associative array of Namespace => mapping definition
     *
     * @return array
     */
    function getEntityMappings()
    {

        return array(
            'AppModule\Entities' => dirname(__DIR__) . '*Entity.php',
        );
    }
}
